import http from "node:http";
import pg from "pg";
import {config} from "./config.mjs";
import {Wal} from "./wal/wal.mjs";
import {PostgresQueue} from "./queue/postgres-queue.mjs";
import {normalizeEvent} from "./normalize/normalize.mjs";
const pool=config.databaseUrl?new pg.Pool({connectionString:config.databaseUrl,max:10,idleTimeoutMillis:30000}):null;
const wal=new Wal(config.walDir);await wal.init();
if(pool){await pool.query("CREATE TABLE IF NOT EXISTS ingestion_events(id BIGSERIAL PRIMARY KEY,fingerprint TEXT NOT NULL UNIQUE,source TEXT NOT NULL,sequence BIGINT,observed_at TIMESTAMPTZ NOT NULL DEFAULT now(),payload JSONB NOT NULL,status TEXT NOT NULL DEFAULT 'queued' CHECK(status IN ('queued','processing','processed','failed')),attempts INTEGER NOT NULL DEFAULT 0,lease_token UUID,lease_until TIMESTAMPTZ,last_error TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());CREATE INDEX IF NOT EXISTS ingestion_events_queue_idx ON ingestion_events(status,id);CREATE INDEX IF NOT EXISTS ingestion_events_lease_idx ON ingestion_events(status,lease_until);CREATE TABLE IF NOT EXISTS opportunities(id BIGSERIAL PRIMARY KEY,fingerprint TEXT NOT NULL UNIQUE,kind TEXT NOT NULL,chain_id INTEGER,token_in TEXT,token_out TEXT,buy_pool TEXT,sell_pool TEXT,gross_edge_bps NUMERIC NOT NULL,estimated_gas_usd NUMERIC,estimated_slippage_usd NUMERIC,estimated_net_profit_usd NUMERIC,observed_at TIMESTAMPTZ NOT NULL,payload JSONB NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());CREATE INDEX IF NOT EXISTS opportunities_rank_idx ON opportunities(estimated_net_profit_usd DESC NULLS LAST,observed_at DESC)");}
const queue=pool?new PostgresQueue(pool):null;
async function ingest(source,payload,sequence=null){const e=normalizeEvent({source,payload,sequence});await wal.append(e);if(queue)await queue.enqueue(e);return e}
async function work(){if(!queue)return;await queue.recoverExpired();for(const j of await queue.claim(config.workerBatchSize)){try{if(j.payload?.opportunity)await queue.saveOpportunity(j.payload.opportunity,j.observed_at);await queue.process(j,async()=>{})}catch(e){await queue.fail(j,e);console.error("job",e)}}}
const timer=setInterval(()=>work().catch(console.error),config.pollMs);
function json(res,status,data){res.writeHead(status,{"content-type":"application/json; charset=utf-8","cache-control":"no-store","access-control-allow-origin":"*"});res.end(JSON.stringify(data))}
async function read(req){let s="";for await(const c of req){s+=c;if(s.length>1048576)throw Error("request too large")}return s?JSON.parse(s):{}}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,"http://localhost");if(req.method==="GET"&&u.pathname==="/"){res.writeHead(200,{"content-type":"text/html; charset=utf-8"});return res.end("<h1>Opportunity Feed Intelligence</h1><p>Standalone engine online.</p><ul><li><a href='/health'>Health</a></li><li><a href='/api/opportunities'>Opportunities</a></li></ul>")}if(req.method==="GET"&&u.pathname==="/health"){return json(res,200,{status:"ok",service:"opportunity-feed-intelligence",standalone:true,postgres:Boolean(pool),rpc:Boolean(config.rpcUrl),queue:queue?await queue.stats():null})}if(req.method==="POST"&&u.pathname==="/api/ingest"){const b=await read(req);if(!b.source)return json(res,400,{error:"source required"});return json(res,202,{ok:true,event:await ingest(b.source,b.payload,b.sequence??null)})}if(req.method==="GET"&&u.pathname==="/api/opportunities"){if(!pool)return json(res,503,{error:"PostgreSQL is not configured"});const r=await pool.query("SELECT id,kind,chain_id,token_in,token_out,buy_pool,sell_pool,gross_edge_bps,estimated_gas_usd,estimated_slippage_usd,estimated_net_profit_usd,observed_at FROM opportunities ORDER BY estimated_net_profit_usd DESC NULLS LAST,observed_at DESC LIMIT 100");return json(res,200,{items:r.rows})}return json(res,404,{error:"not found"})}catch(e){return json(res,500,{error:String(e?.message||e)})}});
server.listen(config.port,"0.0.0.0",()=>console.log("opportunity engine listening on "+config.port));
async function shutdown(){clearInterval(timer);server.close();if(queue)await queue.shutdown();if(pool)await pool.end();process.exit(0)}process.on("SIGTERM",shutdown);process.on("SIGINT",shutdown);