import crypto from "node:crypto";
const ALG="aes-256-gcm", NONCE=12, TAG=16;
function canon(v){if(v===null||typeof v!=="object")return JSON.stringify(v);if(Array.isArray(v))return "["+v.map(canon).join(",")+"]";return "{"+Object.keys(v).sort().map(k=>JSON.stringify(k)+":"+canon(v[k])).join(",")+"}"}
function key(secret){return crypto.createHash("sha256").update(String(secret)).digest()}
async function probe(url){const t=performance.now();try{const r=await fetch(url,{method:"HEAD",redirect:"error",signal:AbortSignal.timeout(3000)});return{healthy:r.ok||r.status===204,rttMs:performance.now()-t,status:r.status}}catch(e){return{healthy:false,rttMs:performance.now()-t,status:0,error:String(e?.message||e)}}}
export class PrivateMesh{
constructor({secret,nodeId=crypto.randomUUID(),peers=[],maxLanes=4}){if(!secret)throw new Error("MESH_SECRET is required");this.secret=String(secret);this.key=key(this.secret);this.nodeId=String(nodeId);this.maxLanes=Math.max(1,Math.min(16,Number(maxLanes)||4));const kp=crypto.generateKeyPairSync("ed25519");this.privateKey=kp.privateKey;this.publicKey=kp.publicKey.export({format:"der",type:"spki"}).toString("base64");this.peers=new Map();for(const p of peers)this.upsertPeer(p);this.state={status:"ready",selected:[],healthy:0,checkedAt:null}}
signManifest(payload){const body=canon(payload);return{payload,signature:crypto.sign(null,Buffer.from(body),this.privateKey).toString("base64"),nodeId:this.nodeId,publicKey:this.publicKey}}
upsertPeer(peer){if(!peer?.id||!Array.isArray(peer.endpoints)||!peer.endpoints.length)return false;this.peers.set(String(peer.id),{id:String(peer.id),endpoints:[...new Set(peer.endpoints.map(String).filter(Boolean))].slice(0,8),weight:Math.max(.1,Number(peer.weight)||1)});return true}
async refresh(){const all=[];await Promise.all([...this.peers.values()].map(async p=>{const r=await Promise.all(p.endpoints.map(probe));r.forEach((x,i)=>all.push({...x,peerId:p.id,endpoint:p.endpoints[i],weight:p.weight}))}));const healthy=all.filter(x=>x.healthy).sort((a,b)=>(a.rttMs+1)/a.weight-(b.rttMs+1)/b.weight);this.state={status:healthy.length?"connected":"degraded",selected:healthy.slice(0,this.maxLanes),healthy:healthy.length,checkedAt:new Date().toISOString()};return this.state}
encrypt(payload,aad=""){const iv=crypto.randomBytes(NONCE);const c=crypto.createCipheriv(ALG,this.key,iv,{authTagLength:TAG});c.setAAD(Buffer.from(String(aad)));const out=Buffer.concat([c.update(JSON.stringify(payload)),c.final()]);return{algorithm:ALG,iv:iv.toString("base64"),tag:c.getAuthTag().toString("base64"),ciphertext:out.toString("base64"),aad:String(aad)}}
decrypt(packet){if(packet?.algorithm!==ALG)throw new Error("unsupported packet");const d=crypto.createDecipheriv(ALG,this.key,Buffer.from(packet.iv,"base64"),{authTagLength:TAG});d.setAAD(Buffer.from(String(packet.aad||"")));d.setAuthTag(Buffer.from(packet.tag,"base64"));return JSON.parse(Buffer.concat([d.update(Buffer.from(packet.ciphertext,"base64")),d.final()]).toString("utf8"))}
status(){return{...this.state,nodeId:this.nodeId,peerCount:this.peers.size,lanes:this.state.selected.length}}
}